Feature
eserengo/Hello-Microverse pull request #1
Opened 2022-08-16 22:14 UTC by eserengo

In this project the objectives are:
Create branches with different base branches.
Understand the concept of version control.
Follow GitHub flow.
Open pull requests in GitHub.
Write descriptive, easy-to-understand commit messages.
Write short, detailed, easy-to-understand descriptions of pull requests.
Write a descriptive and easy-to-understand README in business English for every project submitted.
Demonstrate an ability to submit a project for code review.

The general requirements for this project are:
Make sure that there are no linter errors.
Make sure that you used the correct GitHub flow.
Make sure that you documented your work.

After creating a new GitHub repo, these requirements were added in the feature branch:
Create a new branch according to the GitHub flow.
Add a .gitignore file.
Set up a linter for HTML and CSS and make sure that any files that are not relevant are ignored by git.
Add a descriptive README file to your project.
Add 3 files (each one in a separate commit):
A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
A .css file that includes one class with styles for your header (make it in your favorite color).
A test.md file with the text "This file should be ignored by git".
Make sure that the last file is actually ignored by git and is not present in your GitHub repository.
Open a pull request.

2022-08-16 22:28 UTC, mukhammadrizooff requested changes
Hi @eserengo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Descriptive commit history ✔️ 
- Descriptive PR description ✔️ 
- Perfect `README.md` file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 22:28 UTC, mukhammadrizooff commented on test.md
> +"This file should be ignored by git".
- [ ] [REQUIRED] Good job so far! This file should not appear in your code base because you should have ignored it. To fix the problem, delete and recreate the `test.md` file. After that, make sure that the newly created `test.md` file is ignored!

![image](https://user-images.githubusercontent.com/63915024/184995465-63582344-98ad-45c6-8136-e8aba52ee204.png)

2022-08-16 23:35 UTC, eserengo commented on test.md
> +"This file should be ignored by git".
Hello Muhammad nice to meet you, thank you for your feedback.
I want to make you a question if I may: after I delete the test.md file and create a new one, how do I make sure is ignored? Because I included it in my .gitignore file. What I am missing?

2022-08-17 00:01 UTC, eserengo commented on test.md
> +"This file should be ignored by git".
Hello @mukhammadrizooff nice to meet you, thank you for your feedback.
I want to make you a question if I may: after I delete the test.md file and create a new one, how do I make sure is ignored? Because I included it in my .gitignore file. What I am missing?
Also, I want to ask how I use the same pull request after I've made all the suggested changes and don't create a new one.
Sorry about all these questions, I'm new to this and I could use a little bit of help.
Thank you.

2022-08-17 16:03 UTC, eserengo commented on test.md
> +"This file should be ignored by git".
@mukhammadrizooff 
August 17, 2022
Added Requested changes:
-Deleted old test.md file
-Created a new test.md file
-Updated .gitignore file.
-Executed the following command: git rm -r --cached .  to clear the cache.

2022-08-17 17:01 UTC, HAMMAS-SALEEM approved these changes
# First of all Welcome Back to Microverse :tada: :bouquet:
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @eserengo :wave:

Great work on implementing the changes requested by previous reviewer. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Documented work in a professional way
:heavy_check_mark: PR Summary is descriptive

### [Optional]

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 17:01 UTC, HAMMAS-SALEEM commented on package.json
> +}
### Your MIT link in your Readme file
![mit](https://user-images.githubusercontent.com/93039359/185199214-c7fbd428-3850-4e3c-a097-5dc8c656f492.png)
**[Optional]**
- [ ] Your MIT.md file is not accessible from your readme file because the link is not the correct link. Make your like something like below :+1:
`This project is [MIT](./MIT.md) licensed.`

2022-08-17 17:20 UTC, eserengo commented
Thank you @HAMMAS-SALEEM for this invaluable feedback.
I've taken note of every suggestion and I'll make sure to implement them in my next projects.
I wonder if I can leave you a question, please. What's my next step with this project, should I merge the pull request?

2022-08-17 17:32 UTC, merged